name: sspanel_签到

on:
  schedule:
    - cron: 0 22,14 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 安装依赖包
      run: |
        pip install -r requirements.txt
    - name: 执行签到
      run: |
        echo -n "This IP is: " 
        curl -s ifconfig.me
        echo ' '
        
        host='${{ secrets.HOST }}'
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        
        host_list=()
        user_list=()
        pwd_list=()
        

        IFS=$'\n'
        for h in ${host[*]}
        do
        host_list[${#host_list[*]}]=${h}
        done

        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done

        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done

        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}

        if [ $user_num != $pwd_num ];then
        echo "账号和密码数量不相等"
        exit 1
        else
        echo "共有 $user_num 个账号，开始签到"
        fi

        for ((i=0;i<$user_num;i++))
        do
        python3 checkin.py <<EOF
        ${host_list[$i]}
        ${user_list[$i]}
        ${pwd_list[$i]}
        EOF
        done
